apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kubernetes
spec:
  selector:
    matchLabels:
      app: spring-kubernetes
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-kubernetes
    spec:
      containers:
        - name: spring-kubernetes
          image: spring-kubernetes:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: postgres-conf
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: name
                  name: postgres-conf
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgres_user
                  name: postgres-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres_password
                  name: postgres-secrets


---
apiVersion: v1
kind: Service
metadata:
  name: spring-kubernetes-service
spec:
  selector:
    app: spring-kubernetes
  ports:
    - protocol: "TCP"
      port: 8080 #the port that the service is running on in the cluster
      targetPort: 8080 # the port exposed by the service
  type: NodePort # type of the service


